- name: NAT Overload configuration
  hosts: cisco_l3
  connection: local
  gather_facts: no
  tags: ipv4
  vars:
    templates_folder: 'templates/{{ vendor }}/{{ dev_type }}'
    staging_nat_folder: 'files/staging/nat'
    parsed_nat_configuration_file: '{{ staging_nat_folder }}/{{ inventory_hostname }}.conf'
    commit_config: true
  tasks:
    - block:
      - name: Create folders for parsed nat configuration
        file:
          path: "{{ staging_nat_folder }}"
          state: directory
        check_mode: no

      - name: Set no conf commit variable (enable testing mode)
        set_fact:
          commit_config: false
        when: ansible_check_mode

      - name: Parse source_nat_overload template
        template:
          src: '{{ templates_folder }}/source_nat_overload.j2'
          dest: '{{ parsed_nat_configuration_file }}'
        check_mode: no

      - name: Load and commit configuration
        napalm_install_config:
          provider: "{{ napalm_provider }}"
          config_file: '{{ parsed_nat_configuration_file }}'
          replace_config: false
          commit_changes: "{{ commit_config }}"
        register: result

      - name: Clean temporary folders/files
        file:
          state: absent
          path: "{{ staging_nat_folder }}"
        check_mode: no

      - name: Print differences in configs
        debug:
          msg: "{{ result | to_nice_yaml }}"
      when: nat_overload_config is defined
