---
- name: Network devices connection testing (ping)
  hosts: network_devices
  connection: local
  gather_facts: no
  tags:
    - ping
  vars:
    ping_count: 10
  tasks:
    - block:
      - name: Ping to destination
        napalm_ping:
          provider: "{{ napalm_provider }}"
          destination: "{{ item }}"
          timeout: 60
          count: "{{ ping_count }}"
        register: result
        with_items: "{{ ping_testing }}"

      - name: Define packet loss when error occured
        set_fact:
          result: "{{ item | default({}) | combine ({ 'packet_loss' : '100' }) }}"
        with_items: "{{ result.results }}"

      - name: Print data
        debug:
          msg: "{{ result | to_nice_yaml }}"
