- name: OSPFv2 configuration
  hosts: routers, cisco_l3
  connection: local
  gather_facts: no
  tags: ipv4
  vars:
    templates_folder: 'templates/{{ vendor }}/{{ dev_type }}'
    staging_ospf_folder: 'files/staging/ospf'
    parsed_ospf_configuration_file: '{{ staging_ospf_folder }}/{{ inventory_hostname }}.conf'
    commit_config: true
  tasks:
    - block:
      - name: Create folders for parsed ospf configuration
        file:
          path: "{{ staging_ospf_folder }}"
          state: directory
        check_mode: no

      - name: Set no conf commit variable (enable testing mode)
        set_fact:
          commit_config: false
        when: ansible_check_mode

      - name: Parse ospf_ipv4 template
        template:
          src: '{{ templates_folder }}/ospf_ipv4.j2'
          dest: '{{ parsed_ospf_configuration_file }}'
        check_mode: no

      - name: Load and commit configuration
        napalm_install_config:
          provider: "{{ napalm_provider }}"
          config_file: '{{ parsed_ospf_configuration_file }}'
          replace_config: false
          commit_changes: "{{ commit_config }}"
        register: result

      - name: Clean temporary folders/files
        file:
          state: absent
          path: "{{ staging_ospf_folder }}"
        check_mode: no

      - name: Print differences in configs
        debug:
          msg: "{{ result | to_nice_yaml }}"
      when: ospf_config is defined

- name: OSPFv3 configuration
  hosts: routers
  connection: local
  gather_facts: no
  tags: ipv6
  vars:
    templates_folder: 'templates/{{ vendor }}/{{ dev_type }}'
    staging_ospf_folder: 'files/staging/ospf'
    parsed_ospf_configuration_file: '{{ staging_ospf_folder }}/{{ inventory_hostname }}.conf'
    commit_config: true
  tasks:
    - block:
      - name: Create folders for parsed ospf configuration
        file:
          path: "{{ staging_ospf_folder }}"
          state: directory
        check_mode: no

      - name: Set no conf commit variable (enable testing mode)
        set_fact:
          commit_config: false
        when: ansible_check_mode

      - name: Parse ospfv3 template
        template:
          src: '{{ templates_folder }}/ospfv3.j2'
          dest: '{{ parsed_ospf_configuration_file }}'
        check_mode: no

      - name: Load and commit configuration
        napalm_install_config:
          provider: "{{ napalm_provider }}"
          config_file: '{{ parsed_ospf_configuration_file }}'
          replace_config: false
          commit_changes: "{{ commit_config }}"
        register: result

      - name: Clean temporary folders/files
        file:
          state: absent
          path: "{{ staging_ospf_folder }}"
        check_mode: no

      - name: Print differences in configs
        debug:
          msg: "{{ result | to_nice_yaml }}"
      when: ospfv3_config is defined
