- name: IPv4 packet filter configuration
  hosts: routers, cisco_l3
  connection: local
  gather_facts: no
  tags: ipv4
  vars:
    templates_folder: 'templates/{{ vendor }}/{{ dev_type }}'
    staging_packet_filter_folder: 'files/staging/packet_filter'
    parsed_packet_filter_configuration_file: '{{ staging_packet_filter_folder }}/{{ inventory_hostname }}.conf'
    commit_config: true
  tasks:
    - block:
      - name: Create folders for parsed packet filter configuration
        file:
          path: "{{ staging_packet_filter_folder }}"
          state: directory
        check_mode: no

      - name: Set no conf commit variable (enable testing mode)
        set_fact:
          commit_config: false
        when: ansible_check_mode

      - name: Parse packet_filter_ipv4 template
        template:
          src: '{{ templates_folder }}/packet_filter_ipv4.j2'
          dest: '{{ parsed_packet_filter_configuration_file }}'
        check_mode: no

      - name: Load and commit configuration
        napalm_install_config:
          provider: "{{ napalm_provider }}"
          config_file: '{{ parsed_packet_filter_configuration_file }}'
          replace_config: false
          commit_changes: "{{ commit_config }}"
        register: result

      - name: Clean temporary folders/files
        file:
          state: absent
          path: "{{ staging_packet_filter_folder }}"
        check_mode: no

      - name: Print differences in configs
        debug:
          msg: "{{ result | to_nice_yaml }}"
      when: packet_filter_config is defined

- name: IPv6 packet filter configuration
  hosts: routers, cisco_l3
  connection: local
  gather_facts: no
  tags: ipv6
  vars:
    templates_folder: 'templates/{{ vendor }}/{{ dev_type }}'
    staging_packet_filter_folder: 'files/staging/packet_filter'
    parsed_packet_filter_configuration_file: '{{ staging_packet_filter_folder }}/{{ inventory_hostname }}.conf'
    commit_config: true
  tasks:
    - block:
      - name: Create folders for parsed packet filter configuration
        file:
          path: "{{ staging_packet_filter_folder }}"
          state: directory
        check_mode: no

      - name: Set no conf commit variable (enable testing mode)
        set_fact:
          commit_config: false
        when: ansible_check_mode

      - name: Parse packet_filter_ipv6 template
        template:
          src: '{{ templates_folder }}/packet_filter_ipv6.j2'
          dest: '{{ parsed_packet_filter_configuration_file }}'
        check_mode: no

      - name: Load and commit configuration
        napalm_install_config:
          provider: "{{ napalm_provider }}"
          config_file: '{{ parsed_packet_filter_configuration_file }}'
          replace_config: false
          commit_changes: "{{ commit_config }}"
        register: result

      - name: Clean temporary folders/files
        file:
          state: absent
          path: "{{ staging_packet_filter_folder }}"
        check_mode: no

      - name: Print differences in configs
        debug:
          msg: "{{ result | to_nice_yaml }}"
      when: packet_filter_ipv6_config is defined