---
# YAML soubor, který slouží POUZE jako přehled VŠECH definovatelných možností nastavení inventáře pro ubuntu servery (Ubuntu verze 18.04). Nejedná se o reálný příklad.
# Je zde definována struktura a formát dat pro jednotlivé konfigurace zařízení.
---
ansible_host: 10.10.10.10
vendor: debian
dev_type: ubuntu_server
vsftpd_config: # vsftpd konfigurace, nepovinné fieldy: ssl
  vsftpd_user:
    name: ftpuser
    password: "{{ vault_vsftpd_user_password | string | password_hash('sha512') }}"
    groups: sudo,ftpuser
    home: /home/ftpuser
  ssl:
    enabled: true
    cert_file: /etc/certs/vsftpd_cert.pem
    openssl_csr: /etc/ssl/private/vsftpd.csr
    private_key_file: /etc/certs/vsftpd.pem
    cn: 10.10.10.10

telegraf_ip_address: 10.10.10.10
influxdb_ip_address: 10.10.10.10
influx_db_url: "http://{{ influxdb_ip_address }}:8086"
grafana_url: http://10.10.10.10:3000

grafana_data_sources: # definování zdrojů dat pro Grafanu
  - name: influxsourceAnsible
    ds_type: "influxdb"
    database: "{{ influxdb_ansible_database_name }}"
    url: "{{ influx_db_url }}"
    user: "{{ influxdb_admin_username }}"
    password: "{{ influxdb_admin_password }}"
  - name: influxsourceNornir
    ds_type: "influxdb"
    database: "{{ influxdb_nornir_database_name }}"
    url: "{{ influx_db_url }}"
    user: "{{ influxdb_admin_username }}"
    password: "{{ influxdb_admin_password }}"
  - name: influxsourceTelegraf
    ds_type: "influxdb"
    database: "{{ influxdb_telegraf_database_name }}"
    url: "{{ influx_db_url }}"
    user: "{{ influxdb_admin_username }}"
    password: "{{ influxdb_admin_password }}"