---
ansible_python_interpreter: ~/.local/share/virtualenvs/network_automation_ansible-jyRQ_HBH/bin/python
ansible_network_os: junos
ansible_connection: network_cli
ansible_user: juniper
ansible_password: Juniper
napalm_provider:
  hostname: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  dev_os: "{{ ansible_network_os }}"
  password: "{{ ansible_password }}"
